# Generated by Django 2.2 on 2019-05-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='updated_at',
        ),
    ]
